import type { Metadata } from "next";
import React from "react";
import Header from "@/layout/header";
import Footer from "@/layout/footer";
import Aside from "@/layout/aside";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">

      <body className={`${geistSans.variable} ${geistMono.variable} antialiased min-h-screen flex flex-col gap-5 p-5`}>
        
        <Header />

        <div className="flex flex-1 gap-5">

          <Aside />

          <main className="flex-1 p-8 bg-green-400 flex flex-col justify-center gap-5 rounded">
            {children}
          </main>

        </div>

        <Footer />

      </body>

    </html>
  );
}
